Repository data-apis/array-api, pull requests merged in 2021-06, with the labels that each got.

#196 [Docs] Fix minor rendering bugs
  spec/design_topics/data_interchange.md
  spec/purpose_and_scope.md
  spec/use_cases.md
Labels: maintenance

#201 Update output dtypes for bitwise shift operations
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#194 PR: Add smallest normal to finfo class
  spec/API_specification/data_type_functions.md
Labels: API change

#205 Require unique counts array to be default integer dtype
  spec/API_specification/set_functions.md
Labels: maintenance

#206 Update formatting and organization of dtype guidance
  spec/API_specification/data_types.md
Labels: maintenance

#193 Clarify guidance on operations having data-dependent output shapes
  spec/API_specification/indexing.md
  spec/API_specification/searching_functions.md
  spec/API_specification/set_functions.md
  spec/design_topics/data_dependent_output_shapes.md
  spec/design_topics/index.rst
Labels: content

#204 Clarify `eig` and `eigvals` todos
  spec/extensions/linear_algebra_functions.md
Labels: maintenance

#203 Update guidance on tuple field names
  spec/extensions/linear_algebra_functions.md
Labels: maintenance

#172 Add specification for `__setitem__`
  spec/API_specification/array_object.md
Labels: API extension
