Repository data-apis/array-api, pull requests merged in 2021-08, with the labels that each got.

#241 Remove `axisN` keyword arguments from `linalg.diag` and `linalg.trace`
  spec/extensions/linear_algebra_functions.md
Labels: maintenance

#230 Some improvements to type hints
  spec/API_specification/array_object.md
  spec/API_specification/creation_functions.md
  spec/API_specification/manipulation_functions.md
  spec/API_specification/searching_functions.md
  spec/extensions/linear_algebra_functions.md
Labels: topic: static typing

#236 Split `linalg.norm` into separate vector and matrix APIs
  spec/extensions/linear_algebra_functions.md
Labels: API change, topic: linalg
