Repository data-apis/array-api, pull requests merged in 2021-09, with the labels that each got.

#245 Restrict the `T` attribute to two-dimensional arrays
  spec/API_specification/array_object.md
Labels: API change

#246 Add specification for performing a batched matrix transpose on an array instance via an `.mT` attribute
  spec/API_specification/array_object.md
Labels: API extension

#251 Clarify some text in the logical_* functions
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#253 Fix output array dtype when computing the remainder
  spec/API_specification/elementwise_functions.md
Labels: bug

#171 Improve description of device handling, add `array.to_device`
  spec/API_specification/array_object.md
  spec/design_topics/device_support.md
Labels: content

#260 Clarify output dtype guidance for `mean`, `var`, and `std`
  spec/API_specification/statistical_functions.md
Labels: bug

#263 Add `__index__` to array object
  spec/API_specification/array_object.md
Labels: API extension, topic: indexing

#262 Specify behavior of statistical reductions over the empty set
  spec/API_specification/statistical_functions.md
Labels: maintenance

#238 Add `dtype` keyword argument to `sum` and `prod`
  spec/API_specification/statistical_functions.md
Labels: API change

#247 Rename (and move) `transpose` to `permute_dims`
  spec/API_specification/array_object.md
  spec/API_specification/manipulation_functions.md
Labels: API change, topic: linalg

#243 Add specifications for returning upper (`triu`) and lower (`tril`) triangular matrices
  spec/API_specification/creation_functions.md
Labels: API extension

#226 Remove upper keyword from `eigh` and `eigvalsh`.
  spec/extensions/linear_algebra_functions.md
Labels: API change, topic: linalg

#138 Clarify the exact bounds of what is required for slices
  spec/API_specification/indexing.md
Labels: maintenance

#269 Remove `einsum`
  spec/API_specification/linear_algebra_functions.md
  spec/extensions/linear_algebra_functions.md
Labels: API change, topic: linalg

#250 Indicate that abs() of the minimum integer value for signed dtypes is undefined
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#270 Add note to `negative` for signed integer dtype behavior
  spec/API_specification/array_object.md
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#271 Add note to `__abs__` concerning signed integer dtype behavior
  spec/API_specification/array_object.md
Labels: maintenance

#268 Update device guidance for `*_like` functions
  spec/API_specification/creation_functions.md
Labels: API change

#273 Require that data type objects implement `__eq__` in order to test for data type equality
  spec/API_specification/data_types.md
Labels: API extension

#276 Remove the `Sequence` encapsulation of variadic parameters
  spec/API_specification/creation_functions.md
  spec/API_specification/data_type_functions.md
Labels: topic: static typing

#278 Disallow `k=None` for the `eye` function
  spec/API_specification/creation_functions.md
Labels: topic: static typing
