Repository data-apis/array-api, pull requests merged in 2021-11, with the labels that each got.

#290 Add specification for explicitly casting an array to a specified dtype
  requirements.txt
  spec/API_specification/creation_functions.md
  spec/API_specification/data_type_functions.md
Labels: API extension, topic: creation, topic: type promotion

#296 Add note concerning the casting of boolean input arrays
  spec/API_specification/data_type_functions.md
Labels: content

#280 Add clarifying examples to note concerning tuple usage in multi-axis indexing
  spec/API_specification/indexing.md
Labels: content, topic: indexing

#259 Address a few device related issues
  spec/API_specification/array_object.md
  spec/design_topics/device_support.md
Labels: content

#220 Make the writing of the factorisations in linalg more uniform
  spec/extensions/linear_algebra_functions.md
Labels: topic: linalg

#301 Remove DLPack support from asarray
  spec/API_specification/creation_functions.md
Labels: API change, topic: dlpack

#224 Account for when factorizations and solvers are not well-defined
  spec/extensions/linear_algebra_functions.md
Labels: topic: linalg

#302 Add notes concerning input array validation
  spec/extensions/linear_algebra_functions.md
Labels: maintenance, topic: linalg

#304 Update guidance for linalg `rtol` tolerance cutoff to accommodate non-SVD-like algorithms
  spec/extensions/linear_algebra_functions.md
Labels: maintenance, topic: linalg

#303 Update `slogdet` guidance for when the determinant is zero
  spec/extensions/linear_algebra_functions.md
Labels: maintenance, topic: linalg

#298 Arrays must share the same dtype in `meshgrid()`
  spec/API_specification/creation_functions.md
Labels: maintenance, topic: creation

#299 Clarify in-place operations mirror special case behaviour
  spec/API_specification/array_object.md
Labels: maintenance

#297 Include entry points as an optional feature
  spec/conf.py
  spec/purpose_and_scope.md
Labels: content

#306 Remove obsolete note
  spec/purpose_and_scope.md
Labels: maintenance

#307 Disallow scalar operands when using the matmul operator
  spec/API_specification/type_promotion.md
Labels: content, topic: type promotion

#308 Group operators into separate classes
  spec/API_specification/array_object.md
Labels: maintenance, content

#309 Add guidance concerning how to check for an array API compliant object
  spec/purpose_and_scope.md
Labels: content

#310 Require that NaNs be considered distinct when returning unique elements
  spec/API_specification/set_functions.md
Labels: maintenance

#289 Specify shape behavior
  spec/API_specification/array_object.md
Labels: API change

#313 Update namedtuple field names for `linalg.qr` and `linalg.svd`
  spec/extensions/linear_algebra_functions.md
Labels: maintenance, API change, topic: linalg

#282 Some fixes to the linear algebra functions
  spec/API_specification/array_object.md
  spec/API_specification/linear_algebra_functions.md
  spec/extensions/linear_algebra_functions.md
Labels: maintenance, topic: linalg

#314 Remove obsolete TODOs
  spec/purpose_and_scope.md
Labels: maintenance, content

#315 Add guidance requiring support for zero-dimensional arrays
  spec/API_specification/array_object.md
Labels: content

#316 Add note concerning float sort order
  spec/API_specification/sorting_functions.md
Labels: maintenance

#300 Require static memory allocation for PyCapsule names
  spec/design_topics/data_interchange.md
Labels: topic: dlpack

#311 Add note concerning division by zero for integer dtypes in floor_divide and remainder
  spec/API_specification/array_object.md
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#312 Add guidance for when rounding special floating-point values
  spec/API_specification/elementwise_functions.md
Labels: maintenance

#317 Add `unique_counts()` and fix the description of `unique_all()`
  spec/API_specification/set_functions.md
Labels: maintenance, API extension

#320 Machine readability fixes for operator special cases
  spec/API_specification/array_object.md
Labels: maintenance

#322 Update guidance for default data types
  spec/API_specification/data_types.md
Labels: API change, topic: indexing

#323 Update return data types for those APIs returning indices and counts
  spec/API_specification/set_functions.md
Labels: API change

#324 Fix guidance for tensordot broadcasting
  spec/API_specification/linear_algebra_functions.md
Labels: maintenance, topic: linalg

#305 Disallow providing a stack of vectors to `linalg.solve`
  spec/extensions/linear_algebra_functions.md
Labels: API change, topic: linalg

#327 Update the description of the entry point in purpose and scope
  spec/purpose_and_scope.md
Labels: content

#321 Remove `axis` kwarg support from `linalg.matrix_norm`
  spec/extensions/linear_algebra_functions.md
Labels: API change, topic: linalg

#331 `expand_dims()` signature change (and slight doc fix)
  spec/API_specification/manipulation_functions.md
Labels: maintenance, API change

#328 Fix `matmul` broadcasting guidance
  spec/API_specification/array_object.md
  spec/API_specification/linear_algebra_functions.md
Labels: bug, topic: linalg

#330 Update guidance for `pow` and `divide` concerning arrays with integer dtypes
  spec/API_specification/array_object.md
  spec/API_specification/elementwise_functions.md
Labels: maintenance, API change

#338 Changes Implementation section of data-interchange to close #337
  spec/design_topics/data_interchange.md
Labels: topic: dlpack

#340 Update guidance for unsigned integer data types for `sum` and `prod`
  spec/API_specification/statistical_functions.md
Labels: API change, topic: stats
