Repository data-apis/array-api, pull requests merged in 2022-01, with the labels that each got.

#358 Fix signature for linalg.vecdot
  spec/extensions/linear_algebra_functions.md
Labels: bug, topic: linalg

#357 Change the type annotation for `__array_namespace__` to Any
  spec/API_specification/array_object.md
Labels: topic: static typing

#347 PR: Transform constants.md to rst format
  spec/API_specification/constants.md
  spec/API_specification/constants.rst
  spec/API_specification/signatures/constants.py
Labels: maintenance

#362 Clarify that the results of division operations on integer array data types resulting in floating-point outputs is implementation-defined
  spec/API_specification/array_object.md
  spec/API_specification/elementwise_functions.md
  spec/API_specification/statistical_functions.md
Labels: maintenance

#363 Add the autosummary generated files to .gitignore and 'make clean'
  .gitignore
  spec/Makefile
Labels: maintenance

#346 PR: Transform broadcasting.md to .rst
  spec/API_specification/broadcasting.md
  spec/API_specification/broadcasting.rst
Labels: maintenance

#353 PR: Transform indexing.md to rst
  spec/API_specification/indexing.md
  spec/API_specification/indexing.rst
Labels: maintenance

#345 PR: Convert array_object.md to rst
  .github/workflows/preview.yml
  spec/API_specification/array_object.md
  spec/API_specification/array_object.rst
  spec/API_specification/signatures/_types.py
  spec/API_specification/signatures/array_object.py
  spec/purpose_and_scope.md
Labels: maintenance

#380 PR: Transform parallelism md to rst
  spec/design_topics/parallelism.rst
Labels: maintenance

#381 PR: Transform static typing md to rst
  spec/design_topics/static_typing.rst
Labels: maintenance

#378 PR: Transform data interchange mechanisms md to rst
  spec/design_topics/data_interchange.md
  spec/design_topics/data_interchange.rst
Labels: maintenance

#374 PR: Transform C API md to rst
  spec/design_topics/C_API.md
  spec/design_topics/C_API.rst
Labels: maintenance

#377 PR: Transform data dependent output shapes md to rst
  spec/design_topics/data_dependent_output_shapes.rst
Labels: maintenance

#375 PR: Transform accuracy md to rst
  spec/design_topics/accuracy.md
  spec/design_topics/accuracy.rst
Labels: maintenance

#376 PR: Transform copies views and mutation md to rst
  spec/design_topics/copies_views_and_mutation.rst
Labels: maintenance

#348 Transform creation_functions.md to rst
  spec/API_specification/creation_functions.md
  spec/API_specification/creation_functions.rst
  spec/API_specification/signatures/_types.py
  spec/API_specification/signatures/array_object.py
  spec/API_specification/signatures/creation_functions.py
  spec/conf.py
Labels: maintenance

#372 PR: Transform utility functions md to rst
  spec/API_specification/signatures/utility_functions.py
  spec/API_specification/utility_functions.md
  spec/API_specification/utility_functions.rst
Labels: maintenance

#367 PR: Transform linear algebra functions md to rst
  .circleci/config.yml
  .github/workflows/pages.yml
  spec/API_specification/linear_algebra_functions.md
  spec/API_specification/linear_algebra_functions.rst
  spec/API_specification/signatures/array_object.py
  spec/API_specification/signatures/linear_algebra_functions.py
  spec/extensions/linear_algebra_functions.md
Labels: maintenance

#379 PR: Transform device support md to rst
  spec/design_topics/device_support.md
  spec/design_topics/device_support.rst
Labels: maintenance

#371 PR: Transform type promotion md to rst
  spec/API_specification/type_promotion.md
  spec/API_specification/type_promotion.rst
Labels: maintenance

#370 PR: Transform statistical functions md to rst
  spec/API_specification/signatures/statistical_functions.py
  spec/API_specification/statistical_functions.md
  spec/API_specification/statistical_functions.rst
Labels: maintenance

#369 PR: Transform set functions md to rst
  spec/API_specification/set_functions.md
  spec/API_specification/set_functions.rst
  spec/API_specification/signatures/set_functions.py
Labels: maintenance

#368 PR: Transform searching functions md to rst
  spec/API_specification/searching_functions.md
  spec/API_specification/searching_functions.rst
  spec/API_specification/signatures/searching_functions.py
Labels: maintenance

#354 PR: Transform manipulation_functions.md to rst
  spec/API_specification/manipulation_functions.md
  spec/API_specification/manipulation_functions.rst
  spec/API_specification/signatures/manipulation_functions.py
Labels: maintenance

#351 PR: Transform elementwise_functions.md to rst
  spec/API_specification/elementwise_functions.md
  spec/API_specification/elementwise_functions.rst
  spec/API_specification/signatures/array_object.py
  spec/API_specification/signatures/elementwise_functions.py
Labels: maintenance
