Repository data-apis/array-api, pull requests merged in 2022-05, with the labels that each got.

#420 Add admonition concerning array view mutation
  spec/design_topics/copies_views_and_mutation.rst
Labels: content

#394 Add a version menu to the Sphinx build
  spec/conf.py
Labels: deployment

#422 Fix failing preview.yml GitHub Actions job
  .github/workflows/preview.yml
Labels: maintenance

#432 PR: Add sphinx math dollar extension
  requirements.txt
  spec/conf.py
Labels: maintenance

#426 Move broadcast functions to list of functions for manipulating arrays
  spec/API_specification/data_type_functions.rst
  spec/API_specification/manipulation_functions.rst
  spec/API_specification/signatures/data_type_functions.py
  spec/API_specification/signatures/manipulation_functions.py
Labels: maintenance, topic: broadcasting

#418 Add complex floating-point data types
  spec/API_specification/array_object.rst
  spec/API_specification/data_types.rst
  spec/API_specification/signatures/array_object.py
  spec/API_specification/signatures/creation_functions.py
  spec/API_specification/signatures/data_type_functions.py
  spec/API_specification/signatures/elementwise_functions.py
  spec/API_specification/signatures/linalg.py
  spec/API_specification/signatures/linear_algebra_functions.py
  spec/API_specification/signatures/searching_functions.py
  spec/API_specification/signatures/statistical_functions.py
Labels: API extension, topic: complex dtypes

#430 PR: Rename `signatures` module to array_api
  spec/API_specification/array_api/__init__.py
  spec/API_specification/array_api/_types.py
  spec/API_specification/array_api/array_object.py
  spec/API_specification/array_api/constants.py
  spec/API_specification/array_api/creation_functions.py
  spec/API_specification/array_api/data_type_functions.py
  spec/API_specification/array_api/data_types.py
  spec/API_specification/array_api/elementwise_functions.py
  spec/API_specification/array_api/linalg.py
  spec/API_specification/array_api/linear_algebra_functions.py
  spec/API_specification/array_api/manipulation_functions.py
  spec/API_specification/array_api/searching_functions.py
  spec/API_specification/array_api/set_functions.py
  spec/API_specification/array_api/sorting_functions.py
  spec/API_specification/array_api/statistical_functions.py
  spec/API_specification/array_api/utility_functions.py
  spec/API_specification/array_object.rst
  spec/API_specification/constants.rst
  spec/API_specification/creation_functions.rst
  spec/API_specification/data_type_functions.rst
  spec/API_specification/data_types.rst
  spec/API_specification/elementwise_functions.rst
  spec/API_specification/indexing.rst
  spec/API_specification/linear_algebra_functions.rst
  spec/API_specification/manipulation_functions.rst
  spec/API_specification/searching_functions.rst
  spec/API_specification/set_functions.rst
  spec/API_specification/signatures/__init__.py
  spec/API_specification/sorting_functions.rst
  spec/API_specification/statistical_functions.rst
  spec/API_specification/utility_functions.rst
  spec/Makefile
  spec/conf.py
  spec/extensions/linear_algebra_functions.rst
Labels: enhancement

#439 Update `iinfo` description to be consistent with `finfo`
  spec/API_specification/array_api/data_type_functions.py
Labels: maintenance, content

#444 fixed obvious typo
  spec/design_topics/C_API.rst
Labels: maintenance, content

#437 Add complex number support to `meshgrid`
  spec/API_specification/array_api/creation_functions.py
Labels: API change, topic: complex dtypes
