Repository data-apis/array-api, pull requests merged in 2022-02, with the labels that each got.

#384 PR: Transform linear algebra functions extension md to rst
  spec/API_specification/signatures/array_object.py
  spec/API_specification/signatures/linalg.py
  spec/extensions/linear_algebra_functions.md
  spec/extensions/linear_algebra_functions.rst
Labels: maintenance

#349 PR: Transform data_type_functions.md to rst
  spec/API_specification/data_type_functions.md
  spec/API_specification/data_type_functions.rst
  spec/API_specification/signatures/creation_functions.py
  spec/API_specification/signatures/data_type_functions.py
Labels: maintenance

#326 Update "scope of array API" and DLPack structure diagrams
  spec/_static/images/DLPack_diagram.png
  spec/_static/images/scope_of_array_API.png
Labels: maintenance

#387 Fix `axis` description in `expand_dims`
  spec/API_specification/signatures/manipulation_functions.py
Labels: bug, API change, topic: manipulation

#388 Clarify expected results for `any` and `all` when operating on empty arrays
  spec/API_specification/signatures/utility_functions.py
Labels: maintenance, API change

#386 Add `copy` kwarg support to `reshape`
  spec/API_specification/signatures/manipulation_functions.py
Labels: API extension, topic: manipulation

#396 Remove (migrated) DLPack docs from Data Interchange page
  spec/_static/images/DLPack_diagram.png
  spec/design_topics/data_interchange.rst
Labels: content

#395 PR: Fix style issues in rendered page
  spec/API_specification/array_object.rst
  spec/API_specification/constants.rst
  spec/API_specification/searching_functions.rst
  spec/API_specification/set_functions.rst
  spec/API_specification/statistical_functions.rst
  spec/API_specification/utility_functions.rst
  spec/_templates/attribute.rst
  spec/_templates/property.rst
Labels: bug
