Repository data-apis/array-api, pull requests merged in 2023-03, with the labels that each got.

#603 Add imag to elementwise functions table of contents
  spec/2022.12/API_specification/elementwise_functions.rst
  spec/draft/API_specification/elementwise_functions.rst
Labels: bug

#610 Make it clearer that the dtype kinds in isdtype are the string inputs
  src/array_api_stubs/_2022_12/data_type_functions.py
  src/array_api_stubs/_draft/data_type_functions.py
Labels: maintenance

#612 Add favicon
  doc-requirements.txt
  pyproject.toml
  spec/_static/images/favicon.png
  src/_array_api_conf.py
Labels: maintenance

#604 Add `unstack`
  spec/draft/API_specification/manipulation_functions.rst
  src/array_api_stubs/_draft/manipulation_functions.py
Labels: API extension
