Repository data-apis/array-api, pull requests merged in 2023-07, with the labels that each got.

#628 Modify versions menu to keep you on the same page
  spec/_static/javascripts/version_dropdown.js
Labels: maintenance

#649 Fix version menu bug
  spec/_static/javascripts/version_dropdown.js
Labels: maintenance

#650 Fix version menu bug
  spec/_static/javascripts/version_dropdown.js
Labels: maintenance

#661 Fix invalid latex in `qr` function API docstring
  src/array_api_stubs/_2022_12/linalg.py
  src/array_api_stubs/_draft/linalg.py
Labels: bug

#660 Add custom css to avoid line-through decorations in Literal arguments
  spec/_static/css/custom.css
  src/_array_api_conf.py
Labels: bug

#663 Update GitHub preview workflow
  .github/workflows/preview.yml
Labels: deployment
