Repository data-apis/array-api, pull requests merged in 2023-11, with the labels that each got.

#687 Backport type fixes to `__getitem__` to previous specification revisions
  spec/draft/API_specification/indexing.rst
  src/array_api_stubs/_2021_12/array_object.py
  src/array_api_stubs/_2022_12/array_object.py
  src/array_api_stubs/_draft/array_object.py
Labels: topic: indexing, backport

#706 Fix typo in input data type for `conj` specification
  src/array_api_stubs/_2022_12/elementwise_functions.py
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: maintenance, backport

#652 Allow lazy implementations to raise from intrinsically eager functions
  src/array_api_stubs/_draft/array_object.py
Labels: topic: lazy/graph

#708 Add a design topic page on lazy vs. eager implementations
  spec/draft/design_topics/index.rst
  spec/draft/design_topics/lazy_eager.rst
Labels: content, topic: lazy/graph

#702 Revise guidance to require a minimum upper bound for supported ranks
  spec/draft/API_specification/array_object.rst
Labels: content

#714 Remove outdated content from Purpose and Scope document
  spec/2022.12/purpose_and_scope.md
  spec/draft/purpose_and_scope.md
Labels: content, backport
