Repository data-apis/array-api, pull requests merged in 2024-10, with the labels that each got.

#844 docs: add missing subscripts in `sign` definition
  src/array_api_stubs/_2022_12/elementwise_functions.py
  src/array_api_stubs/_2023_12/elementwise_functions.py
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: Maintenance, Narrative Content, Backport

#821 docs: add note that iteration is defined for 1-D arrays
  src/array_api_stubs/_2021_12/array_object.py
  src/array_api_stubs/_2022_12/array_object.py
  src/array_api_stubs/_2023_12/array_object.py
  src/array_api_stubs/_draft/array_object.py
Labels: Narrative Content, Needs Discussion

#822 docs: add note that cross-kind comparisons are undefined
  src/array_api_stubs/_draft/array_object.py
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: Narrative Content
