Repository data-apis/array-api, pull requests merged in 2024-01, with the labels that each got.

#699 Add `searchsorted` to the specification
  spec/draft/API_specification/searching_functions.rst
  src/array_api_stubs/_draft/searching_functions.py
Labels: API extension

#729 Fix sidebar contents under Extensions
  spec/draft/extensions/index.rst
Labels: maintenance

#715 Add `clip` to the specification
  spec/draft/API_specification/elementwise_functions.rst
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: API extension

#730 A few updates to the "function and method signatures" section
  spec/draft/API_specification/function_and_method_signatures.rst
Labels: content

#735 Upgrade Sphinx version used in doc deployment
  doc-requirements.txt
  spec/2021.12/assumptions.md
  spec/2021.12/purpose_and_scope.md
  spec/2021.12/use_cases.md
  spec/2022.12/assumptions.md
  spec/2022.12/purpose_and_scope.md
  spec/2022.12/use_cases.md
  spec/draft/assumptions.md
  spec/draft/purpose_and_scope.md
  spec/draft/use_cases.md
  src/_array_api_conf.py
Labels: deployment

#736 Fix wording for comparison operators.
  spec/2022.12/API_specification/array_object.rst
  spec/draft/API_specification/array_object.rst
Labels: topic: complex dtypes, backport
