Repository data-apis/array-api, pull requests merged in 2025-02, with the labels that each got.

#885 feat: add `dtype` kwarg support to `fftfreq` and `rfftfreq`
  src/array_api_stubs/_draft/fft.py
Labels: API change

#887 fix: resolve conflicting exception guidance in `__dlpack__`
  src/array_api_stubs/_2023_12/array_object.py
  src/array_api_stubs/_draft/array_object.py
Labels: topic: DLPack, Backport

#889 feat!: apply type promotion rules according to the device context
  src/array_api_stubs/_draft/data_type_functions.py
Labels: API change, topic: Type Promotion

#888 fix: clarify broadcast behavior in `broadcast_to`
  src/array_api_stubs/_draft/manipulation_functions.py
Labels: topic: Broadcasting

#884 feat: add support for real-valued arrays in `real` and `conj`
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: API change, topic: Complex Data Types

#894 docs: clarify support for negative indices in `take` and `take_along_axis`
  src/array_api_stubs/_draft/indexing_functions.py
Labels: Maintenance, topic: Indexing

#871 feat: define complex scalar <op> fp array
  spec/draft/API_specification/type_promotion.rst
Labels: API change, topic: Complex Data Types, topic: Type Promotion

#814 Clarify that `clip` behavior is undefined when `min` or `max` is outside the bounds of `x`
  src/array_api_stubs/_2023_12/elementwise_functions.py
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: Narrative Content, topic: Type Promotion, Needs Discussion

#897 fix: resolve typo in `broadcast_to` to require an exception
  src/array_api_stubs/_draft/manipulation_functions.py
Labels: Maintenance, topic: Manipulation

#895 docs: clarify the expected results for in-place operations for immutable array libraries
  spec/2023.12/API_specification/array_object.rst
  spec/draft/API_specification/array_object.rst
Labels: topic: Type Promotion, Backport

#896 docs: clarify `clip` behavior when arguments have different data types
  src/array_api_stubs/_2023_12/elementwise_functions.py
  src/array_api_stubs/_draft/elementwise_functions.py
Labels: API change, topic: Type Promotion

#898 fix: address incorrect boundary conditions in `searchsorted`
  src/array_api_stubs/_2023_12/searching_functions.py
  src/array_api_stubs/_draft/searching_functions.py
Labels: Maintenance, Backport

#900 feat: add support for integer array indexing
  spec/draft/API_specification/indexing.rst
  src/array_api_stubs/_draft/array_object.py
Labels: API extension, topic: Indexing

#904 fix: address typo in return type for `nonzero`
  src/array_api_stubs/_2021_12/searching_functions.py
  src/array_api_stubs/_2022_12/searching_functions.py
  src/array_api_stubs/_2023_12/searching_functions.py
Labels: Maintenance, topic: Static Typing, Backport

#906 docs: add design topic on `copy` keyword argument behavior
  spec/draft/design_topics/copies_views_and_mutation.rst
  src/array_api_stubs/_draft/array_object.py
  src/array_api_stubs/_draft/creation_functions.py
  src/array_api_stubs/_draft/data_type_functions.py
  src/array_api_stubs/_draft/manipulation_functions.py
Labels: Narrative Content

#903 docs: add changelog for v2024.12 specification revision
  CHANGELOG.md
  src/array_api_stubs/_draft/array_object.py
  src/array_api_stubs/_draft/data_type_functions.py
  src/array_api_stubs/_draft/elementwise_functions.py
  src/array_api_stubs/_draft/fft.py
  src/array_api_stubs/_draft/indexing_functions.py
  src/array_api_stubs/_draft/info.py
  src/array_api_stubs/_draft/linalg.py
  src/array_api_stubs/_draft/manipulation_functions.py
  src/array_api_stubs/_draft/searching_functions.py
  src/array_api_stubs/_draft/statistical_functions.py
  src/array_api_stubs/_draft/utility_functions.py
Labels: Narrative Content

#908 docs: fix changelog links
  CHANGELOG.md
Labels: Maintenance
